In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(np.random.randn(5, 4))

In [4]:
df

0         1         2         3
0 -0.557641  0.447418 -1.786485  0.238464
1 -0.203519 -1.061182  2.327192  0.220199
2 -1.584963  0.913788 -2.661345 -1.216508
3  0.236147 -0.100994 -1.571183  0.466248
4 -0.143017  2.132116  0.163078  0.430829

In [5]:
np.abs(df)

0         1         2         3
0  0.557641  0.447418  1.786485  0.238464
1  0.203519  1.061182  2.327192  0.220199
2  1.584963  0.913788  2.661345  1.216508
3  0.236147  0.100994  1.571183  0.466248
4  0.143017  2.132116  0.163078  0.430829

In [6]:
df

0         1         2         3
0 -0.557641  0.447418 -1.786485  0.238464
1 -0.203519 -1.061182  2.327192  0.220199
2 -1.584963  0.913788 -2.661345 -1.216508
3  0.236147 -0.100994 -1.571183  0.466248
4 -0.143017  2.132116  0.163078  0.430829

In [7]:
f = lambda x:x.max()
df.apply(f)

0    0.236147
1    2.132116
2    2.327192
3    0.466248
dtype: float64

In [8]:
df.apply(f, axis=1)

0    0.447418
1    2.327192
2    0.913788
3    0.466248
4    2.132116
dtype: float64

In [9]:
df.apply(f, axis=0)

0    0.236147
1    2.132116
2    2.327192
3    0.466248
dtype: float64

In [10]:
df.loc(0)

In [13]:
print(df.iloc[0])

0   -0.557641
1    0.447418
2   -1.786485
3    0.238464
Name: 0, dtype: float64


In [14]:
f2 = lambda x: '%.2f'%x
df.applymap(f2)

0      1      2      3
0  -0.56   0.45  -1.79   0.24
1  -0.20  -1.06   2.33   0.22
2  -1.58   0.91  -2.66  -1.22
3   0.24  -0.10  -1.57   0.47
4  -0.14   2.13   0.16   0.43

In [16]:
s1 = pd.Series(np.arange(4), index =list('dbca'))

In [17]:
s1

d    0
b    1
c    2
a    3
dtype: int32

In [18]:
s1.sort_index()

a    3
b    1
c    2
d    0
dtype: int32

In [19]:
s1

d    0
b    1
c    2
a    3
dtype: int32

In [20]:
s1.sort_index(ascending=False)

d    0
c    2
b    1
a    3
dtype: int32

In [21]:
s1

d    0
b    1
c    2
a    3
dtype: int32

In [23]:
pd1 = pd.DataFrame(np.arange(12).reshape(4,3), index=list("bdcd"), columns=list("BCA"))

In [24]:
pd1

B   C   A
b  0   1   2
d  3   4   5
c  6   7   8
d  9  10  11

In [25]:
pd1.sort_index()

B   C   A
b  0   1   2
c  6   7   8
d  3   4   5
d  9  10  11

In [26]:
pd1.sort_index(axis=1)

A  B   C
b   2  0   1
d   5  3   4
c   8  6   7
d  11  9  10

In [27]:
pd1.sort_index(axis=0)

B   C   A
b  0   1   2
c  6   7   8
d  3   4   5
d  9  10  11

In [3]:
import numpy as np
a = np.random.random((3, 4))

In [4]:
a

array([[0.73298951, 0.21524461, 0.59904222, 0.3652803 ],
       [0.98865855, 0.00478977, 0.83474527, 0.66509791],
       [0.38704104, 0.43965496, 0.87851765, 0.06151746]])

In [7]:
b = np.array([[1],[2],[3]])


In [8]:
b.shape

(3, 1)

In [9]:
a.shape

(3, 4)

In [10]:
c = a+b

In [11]:
c

array([[1.73298951, 1.21524461, 1.59904222, 1.3652803 ],
       [2.98865855, 2.00478977, 2.83474527, 2.66509791],
       [3.38704104, 3.43965496, 3.87851765, 3.06151746]])

In [12]:
a.itemsize

8

In [13]:
a.dtype.itemsize

8

In [14]:
a.data

In [15]:
a.data[0]

NotImplementedError: multi-dimensional sub-views are not implemented

In [16]:
a.size

12

In [17]:
a

array([[0.73298951, 0.21524461, 0.59904222, 0.3652803 ],
       [0.98865855, 0.00478977, 0.83474527, 0.66509791],
       [0.38704104, 0.43965496, 0.87851765, 0.06151746]])

In [18]:
a = np.empty((2, 3))

In [19]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a = np.linspace(0, 2, 9)

In [21]:
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
a @ a.T

12.75

In [23]:
a.dot(a.T)

12.75

In [24]:
def f(x, y):
    return 10*x+y

In [25]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [26]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [27]:
b[0,...]

array([0, 1, 2, 3])

In [28]:
b[...,0]

array([ 0, 10, 20, 30, 40])

In [29]:
b.flat

In [30]:
d = np.array(b.flat)

In [31]:
d

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [32]:
d[0] = 99

In [33]:
d

array([99,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [34]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [35]:
e = d.copy()

In [36]:
e

array([99,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [37]:
e[0]=100

In [38]:
e

array([100,   1,   2,   3,  10,  11,  12,  13,  20,  21,  22,  23,  30,
        31,  32,  33,  40,  41,  42,  43])

In [39]:
d

array([99,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [40]:
e

array([100,   1,   2,   3,  10,  11,  12,  13,  20,  21,  22,  23,  30,
        31,  32,  33,  40,  41,  42,  43])

In [41]:
e.size

20

In [42]:
h = e.reshape((4,5))

In [43]:
h

array([[100,   1,   2,   3,  10],
       [ 11,  12,  13,  20,  21],
       [ 22,  23,  30,  31,  32],
       [ 33,  40,  41,  42,  43]])

In [44]:
g = e.reshape((5,4))

In [45]:
g

array([[100,   1,   2,   3],
       [ 10,  11,  12,  13],
       [ 20,  21,  22,  23],
       [ 30,  31,  32,  33],
       [ 40,  41,  42,  43]])

In [46]:
e[5] = 9999

In [47]:
e

array([ 100,    1,    2,    3,   10, 9999,   12,   13,   20,   21,   22,
         23,   30,   31,   32,   33,   40,   41,   42,   43])

In [48]:
g

array([[ 100,    1,    2,    3],
       [  10, 9999,   12,   13],
       [  20,   21,   22,   23],
       [  30,   31,   32,   33],
       [  40,   41,   42,   43]])

In [49]:
h

array([[ 100,    1,    2,    3,   10],
       [9999,   12,   13,   20,   21],
       [  22,   23,   30,   31,   32],
       [  33,   40,   41,   42,   43]])

In [50]:
p = h.T

In [51]:
p

array([[ 100, 9999,   22,   33],
       [   1,   12,   23,   40],
       [   2,   13,   30,   41],
       [   3,   20,   31,   42],
       [  10,   21,   32,   43]])

In [52]:
e[5] = 80000

In [53]:
e

array([  100,     1,     2,     3,    10, 80000,    12,    13,    20,
          21,    22,    23,    30,    31,    32,    33,    40,    41,
          42,    43])

In [54]:
p

array([[  100, 80000,    22,    33],
       [    1,    12,    23,    40],
       [    2,    13,    30,    41],
       [    3,    20,    31,    42],
       [   10,    21,    32,    43]])

In [55]:
p

array([[  100, 80000,    22,    33],
       [    1,    12,    23,    40],
       [    2,    13,    30,    41],
       [    3,    20,    31,    42],
       [   10,    21,    32,    43]])

In [56]:
q = p.resize((10,2))

In [57]:
q

In [58]:
q

In [59]:
p

array([[  100,    22],
       [    1,    23],
       [    2,    30],
       [    3,    31],
       [   10,    32],
       [80000,    33],
       [   12,    40],
       [   13,    41],
       [   20,    42],
       [   21,    43]])

In [60]:
e[5] = 88888

In [61]:
p

array([[  100,    22],
       [    1,    23],
       [    2,    30],
       [    3,    31],
       [   10,    32],
       [88888,    33],
       [   12,    40],
       [   13,    41],
       [   20,    42],
       [   21,    43]])

In [62]:
t = p.reshape(4,-1)

In [63]:
t

array([[  100,    22,     1,    23,     2],
       [   30,     3,    31,    10,    32],
       [88888,    33,    12,    40,    13],
       [   41,    20,    42,    21,    43]])

In [64]:
r = t.ravel()

In [65]:
r

array([  100,    22,     1,    23,     2,    30,     3,    31,    10,
          32, 88888,    33,    12,    40,    13,    41,    20,    42,
          21,    43])

In [66]:
e

array([  100,     1,     2,     3,    10, 88888,    12,    13,    20,
          21,    22,    23,    30,    31,    32,    33,    40,    41,
          42,    43])

In [67]:
e[5] = 9999999

In [68]:
e

array([    100,       1,       2,       3,      10, 9999999,      12,
            13,      20,      21,      22,      23,      30,      31,
            32,      33,      40,      41,      42,      43])

In [69]:
r

array([  100,    22,     1,    23,     2,    30,     3,    31,    10,
          32, 88888,    33,    12,    40,    13,    41,    20,    42,
          21,    43])

In [70]:
t = e.reshape(4, 5)

In [71]:
t

array([[    100,       1,       2,       3,      10],
       [9999999,      12,      13,      20,      21],
       [     22,      23,      30,      31,      32],
       [     33,      40,      41,      42,      43]])

In [72]:
r = t.ravel()

In [73]:
r

array([    100,       1,       2,       3,      10, 9999999,      12,
            13,      20,      21,      22,      23,      30,      31,
            32,      33,      40,      41,      42,      43])

In [74]:
e[5] =777777

In [75]:
e

array([   100,      1,      2,      3,     10, 777777,     12,     13,
           20,     21,     22,     23,     30,     31,     32,     33,
           40,     41,     42,     43])

In [76]:
r

array([   100,      1,      2,      3,     10, 777777,     12,     13,
           20,     21,     22,     23,     30,     31,     32,     33,
           40,     41,     42,     43])

In [77]:
r = t.T.ravel()

In [78]:
r

array([   100, 777777,     22,     33,      1,     12,     23,     40,
            2,     13,     30,     41,      3,     20,     31,     42,
           10,     21,     32,     43])

In [79]:
e[5] = 66666

In [80]:
r

array([   100, 777777,     22,     33,      1,     12,     23,     40,
            2,     13,     30,     41,      3,     20,     31,     42,
           10,     21,     32,     43])